Add logic to calculate semver
wakatime/semver-action pull request #1
Opened 2021-02-23 22:36 UTC by gandarez

This PR creates a new Action which creates a semantic version based on some info extracted from a git repository.

2021-02-24 23:36 UTC, dron22 reviewed
This is quite some code and need some more time here. Will finish the review tomorrow.

2021-02-25 00:33 UTC, gandarez commented
> This is quite some code and need some more time here. Will finish the review tomorrow.

No rush

2021-02-25 21:34 UTC, dron22 requested changes
Some comments/remarks below. Didn't comment on the codebase much, as I have a general concern regarding tests. The test coverage of `generate` package is currently 38.4 %.

I see, that the code is hard to test, because it has a lot of side effects. This is usually a sign, that the code structure can be improved.

Maybe moving out the logic for tag creation could simplify it a little bit:
```yaml
- name: Generate next version
  uses: wakatime/semver-action@v0.1.0
  with:
    auth_token: "token"
- name: Create Release
  uses: actions/create-release@v1
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  with:
  tag_name: ${{ steps.semver-tag.outputs.tag }}
  release_name: Release ${{ steps.semver-tag.outputs.tag }}
```

2021-02-25 21:34 UTC, dron22 commented on cmd/generate/generate.go
> +func defineBumpStrategy(bump, sourceBranch, destBranch, mainBranchName, developBranchName string) (string, string) {
Is it more like `determineBumpStrategy`? Because they are defined already, right? You're choosing the right one out of the existing ones..

2021-02-25 21:34 UTC, dron22 commented on cmd/generate/generate.go
> +		}
If you make an early return here, you can avoid the indentation level.

```suggestion
	if bump != "auto" {
	    return bump, ""
	}
	
	// bugfix into develop branch
	if branchBugfixPrefixRegex.MatchString(sourceBranch) && destBranch == developBranchName {
		return "build", "patch"
	}
```

2021-02-25 21:34 UTC, dron22 commented on cmd/generate/params_test.go
> +
As you intend to cleanup the env variables at the end, the standard go way would be to use `defer` here. The the creation and removal of the env variable is next to each other.
```suggestion
	os.Setenv("INPUT_PREFIX", "v")
	defer os.Unsetenv("INPUT_PREFIX")

	os.Setenv("INPUT_DRY_RUN", "true")
	defer os.Unsetenv("INPUT_DRY_RUN")

```

2021-02-25 21:34 UTC, dron22 commented on cmd/generate/params_test.go
> +
Or in a function:
```suggestion
	os.Setenv("INPUT_PREFIX", "v")
	os.Setenv("INPUT_DRY_RUN", "true")
	defer func() {
	    os.Unsetenv("INPUT_PREFIX")
          os.Unsetenv("INPUT_DRY_RUN")
      }()

```

2021-02-25 21:34 UTC, dron22 commented on pkg/exitcode/exitcode.go
> +package exitcode
Not sure, if we need a separate package for exit codes, as we only have 2 different action codes and they are only used in one file. Having them as constants on the top of `generate.go` might be enough.

2021-02-26 22:21 UTC, gandarez commented on Makefile
> +build-darwin:
It's just a helper for other developers like me using macOS. I believe it's fair enough to keep it there.

2021-02-26 22:23 UTC, gandarez commented on README.md
> +This action calculates the next version relying on semantic versioning.
fixed it by removing tag creation from its responsability.

2021-02-27 15:56 UTC, gandarez commented on README.md
> +## Example usage
sure no problem.

2021-02-27 16:22 UTC, gandarez commented on README.md
> +### bump
I followed the documentation https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action#creating-a-readme.

2021-02-27 16:23 UTC, gandarez commented on cmd/generate/generate_private_test.go
> +package generate
I've seen some articles using `_private_test`.

2021-02-27 16:31 UTC, gandarez commented
@dron22 fixes applied. Also I removed `tag creation`. There are three separate commits grouping them to maybe make the review easier.

2021-03-06 00:08 UTC, dron22 reviewed
With the added tests, we have a good test coverage now. This is good. Also my intention with my comments also was, to make the structure a little bit simple (e.g. `Run()` function. Usually thinking about how to efficiently test some code will force you to do a good structuring of the code.

Now the overall size grew to an extend, where it is very hard for me to review it. I trust you that it works, but unfortunately, I cannot give a quality review here.

2021-03-06 00:28 UTC, gandarez commented
> With the added tests, we have a good test coverage now. This is good. Also my intention with my comments also was, to make the structure a little bit simple (e.g. `Run()` function. Usually thinking about how to efficiently test some code will force you to do a good structuring of the code.
> 
> Now the overall size grew to an extend, where it is very hard for me to review it. I trust you that it works, but unfortunately, I cannot give a quality review here.

The review actually can be concentrated at source code and all file under `testdata` are just git files to simulate repositories.

2021-03-06 22:16 UTC, dron22 commented
We have to clean up the structure. This is mainly what makes it hard to review. One central issue I see, is that `Run()` is the central piece, but it cannot be covered by unit tests. To illustrate what I mean, in the following an example, for how we can make it unit-testable using an interface:
```
type gitClient interface {
	CurrentBranch() (string, error)
	IsRepo() bool
	LatestTag() (string, error)
	SourceBranch(commitHash string) (string, error)
}

// Run generates a semantic version using the commit sha.
func Run() (Result, error) {
	params, err := LoadParams()
	if err != nil {
		return Result{}, fmt.Errorf("failed to load parameters: %s", err)
	}

	if params.Debug {
		log.SetLevel(log.DebugLevel)
		log.Debug("debug logs enabled\n")
	}

	log.Debug(params.String())

	gc := git.NewGit(p.RepoDir)

	return run(params, gc)
}

func run(params Params, gc gitClient) (Result, error) {}
``` 
The main thing here is the `gitClient` interface. This you can mock in the unit tests and write unit tests for all the scenarios without setting up real git repositories. And these tests will give me a quick and clear overview, of what semver is doing and that everything is working.

The only contexts, where I see a use for the simulated git repositories are:
1. Having a single end-2-end test for the whole action (Following the testing pyramid, these hard-to-setup end-2-end tests are on the top of the pyramid and should only be used very sparsely and not to test variations) 
2. Testing `pkg/git/git.go`. These would be integration tests then.

2021-03-11 23:26 UTC, dron22 requested changes
Alright, this looks nice with the tests!! Now it is easy to grasp, what is going on.

2021-03-11 23:26 UTC, dron22 commented on pkg/git/git.go
> +func (c *Client) LatestTag(prefix string) (*semver.Version, error) {
Here I do not like, that we handle the prefix in the git client. I imagine the git client as providing an interface to git. The fact that we use specific prefix, is part of the business logic and should be handled outside of it.

2021-03-11 23:26 UTC, dron22 commented on pkg/git/git.go
> +			tagStr = prefixRe.ReplaceAllLiteralString(tagStr, "")
This can be replaced by `strings.TrimPrefix`, which is simpler than using a regex function.
```suggestion
tagStr = strings.TrimPrefix(tagStr, prefix)
```

2021-03-11 23:26 UTC, dron22 commented on cmd/generate/generate.go
> +	if tag == nil {
This you normally do not do in golang. Test for error and then additionally test against nil. If we move the prefix logic out of the git client, like commented above, we can avoid this.

2021-03-11 23:26 UTC, dron22 commented on cmd/generate/generate_test.go
> +func newSemVerPtr(t *testing.T, s string) *semver.Version {
`semVerPtr` would be enough here. In this case, the simpler the better.
```suggestion
func semVerPtr(t *testing.T, s string) *semver.Version {
```

2021-03-11 23:26 UTC, dron22 commented on cmd/generate/generate_test.go
> +		"invalid branch name": {
We only increment the alpha version increment, if we have an invalid branch name? What happens, if we had a valid feature branch here? What will be the semver tag? `2.6.19-alpha.2` or `2.7.0-alpha.1`?

Also what happens if the latest tag is `2.6.0-alpha.1` and we merge a feature branch? Will the semver tag be `2.6.0-alpha.2` or `2.7.0-alpha.1`?

2021-03-15 18:29 UTC, gandarez commented on cmd/generate/generate_test.go
> +		"invalid branch name": {
As we rely on having branches prefixed with on of [these](https://github.com/wakatime/semver-action/blob/072749c0059625e1932358b06b27f767d4ea200f/cmd/generate/generate.go#L16) and an unexpected branch arrives we need to at least increment a number to differentiate from the previous one. In this scenario the build number will be incremented.

>We only increment the alpha version increment, if we have an invalid branch name?

Yes

>What happens, if we had a valid feature branch here? What will be the semver tag? 2.6.19-alpha.2 or 2.7.0-alpha.1?

Always we can determine the bumping strategy always we increment it accordingly. Is this case would result as `2.7.0-alpha.1`. For this one I created a new test case called `feature branch into develop when latest tag is alpha`.

> Also what happens if the latest tag is 2.6.0-alpha.1 and we merge a feature branch? Will the semver tag be 2.6.0-alpha.2 or 2.7.0-alpha.1?

This has been answered above.

2021-03-15 18:32 UTC, gandarez commented
@dron22 fixes pushed.

2021-03-18 22:04 UTC, dron22 approved these changes
Alright perfect, this looks good to me :+1: God work :rocket:

2021-03-19 21:41 UTC, merged