Fix git commands
wakatime/semver-action pull request #12
Opened 2021-05-11 13:16 UTC by gandarez

This PR fixes `LatestTag` and `AncestorTag` funcs to correctly validate for string empty.

2021-05-11 20:23 UTC, dron22 requested changes

2021-05-11 20:23 UTC, dron22 commented on pkg/git/git.go
> +	if result != "" {
Usually, there is no guarantee about the content of the first return parameter, in case the error is not nil. To be safe, I would do 2 checks here: 1. Handle a potential error and 2. Check if `result != ""`.

2021-05-11 20:23 UTC, dron22 commented on pkg/git/git.go
> +	if result != "" {
Same here.

2021-05-13 20:24 UTC, gandarez commented on pkg/git/git.go
> +	if result != "" {
Before removing for loop we had the same logic [here](https://github.com/wakatime/semver-action/blob/ea21bc32f18c09c5d3d2f88070b24f6837ec749f/pkg/git/git.go#L161).

2021-05-13 21:54 UTC, dron22 commented on pkg/git/git.go
> +	if result != "" {
Alright, thanks for the additional info. Then I would suggest the following:
```suggestion
	if err != nil || result == "" {
             return c.Clean(c.Run("-C", c.repoDir, "describe", "--tags", "--abbrev=0"))
        }
        
        return result, nil
```
This will correctly handle the case, when git command returns an error. In this case we should ignore first return parameter and execute the fallback command.

2021-05-14 18:24 UTC, gandarez commented
As we discussed `git` commands mixes up many result codes and not always returning an error means an error (strange). For example if we run both commands in a clean repository the first command returns empty but the second returns an error and exits with code 128.

```bash
git tag --points-at HEAD --sort -version:creatordate
git describe --tags --abbrev=0
```

So the last commit I ignored errors for `LatestTag` and `AncestorTag`.

2021-05-14 22:20 UTC, dron22 approved these changes
Alright, so we ignore errors completely. Anyway, in case result will be something invalid, it will fail on semver parsing, right?

2021-05-14 22:28 UTC, gandarez commented
> Alright, so we ignore errors completely. Anyway, in case result will be something invalid, it will fail on semver parsing, right?

Yep I think it's a good approach for that scenario.

2021-05-15 01:25 UTC, merged